- name: Apply Kubernetes deployment
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yml.j2') }}"
    namespace: default

- name: Apply Kubernetes service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'service.yml.j2') }}"
    namespace: default
