pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('DockerHub')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/AhMeD7493/simple-nodejs-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('ahmed7493/nodejs-app:latest')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'DOCKER_HUB_CREDENTIALS') {
                        docker.image('ahmed7493/nodejs-app:latest').push()
                    }
                }
            }
        }

        stage('Deploy with Ansible') {
            steps {
                ansiblePlaybook(
                    playbook: '/home/Ahmed/nodejs-app/ansible/playbook.yml'
		    inventory: '/home/Ahmed/nodejs-app/ansible/inventory/hosts'
                )
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}

